#!/usr/bin/env bash
# Generate .env with auto-generated secrets for the AI platform stack.
#
# Usage:
#   ./scripts/generate-env.sh example.com user@example.com
#   ./scripts/generate-env.sh   # prompts interactively
#
# Generates all passwords, encryption keys, and API keys automatically.
# Saves a copy of generated secrets to .secrets (gitignored) for reference.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"
ENV_FILE="${PROJECT_DIR}/.env"
SECRETS_FILE="${PROJECT_DIR}/.secrets"

# --- Input: domain and email ---
DOMAIN="${1:-}"
ACME_EMAIL="${2:-}"

if [ -z "${DOMAIN}" ]; then
  read -rp "Domain (e.g. example.com): " DOMAIN
fi

if [ -z "${ACME_EMAIL}" ]; then
  read -rp "Email for Let's Encrypt (e.g. user@example.com): " ACME_EMAIL
fi

if [ -z "${DOMAIN}" ] || [ -z "${ACME_EMAIL}" ]; then
  echo "ERROR: Domain and email are required." >&2
  exit 1
fi

# --- Check for existing .env ---
if [ -f "${ENV_FILE}" ]; then
  echo "WARNING: ${ENV_FILE} already exists."
  read -rp "Overwrite? (y/N): " CONFIRM
  if [ "${CONFIRM}" != "y" ] && [ "${CONFIRM}" != "Y" ]; then
    echo "Aborted."
    exit 0
  fi
fi

# --- Generate secrets ---
gen_secret() { openssl rand -base64 "$1" | tr -d '/+=' | head -c "$1"; }
gen_password() { openssl rand -base64 18 | tr -d '/+=' | head -c 16; }

TIMEZONE="${TIMEZONE:-Europe/Berlin}"

FLOWISE_PASSWORD="$(gen_password)"
FLOWISE_SECRET="$(gen_secret 32)"

N8N_PASSWORD="$(gen_password)"
N8N_ENCRYPTION_KEY="$(gen_secret 32)"

QDRANT_API_KEY="$(gen_secret 32)"

LANGFUSE_SECRET="$(gen_secret 32)"
LANGFUSE_AUTH_SECRET="$(gen_secret 32)"
LANGFUSE_SALT="$(gen_secret 32)"
LANGFUSE_DB_PASS="$(gen_password)"

DIFY_SECRET="$(gen_secret 32)"
DIFY_DB_PASS="$(gen_password)"
DIFY_REDIS_PASS="$(gen_password)"
DIFY_SANDBOX_KEY="$(gen_secret 32)"
DIFY_PLUGIN_DAEMON_KEY="$(gen_secret 48)"
DIFY_PLUGIN_INNER_KEY="$(gen_secret 48)"

# --- Write .env ---
cat > "${ENV_FILE}" << EOF
# AI Lab Server Setup — Environment Variables
# Auto-generated by scripts/generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Secrets reference saved to .secrets

# =============================================================================
# General
# =============================================================================
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}
TIMEZONE=${TIMEZONE}

# =============================================================================
# Flowise
# =============================================================================
FLOWISE_VERSION=latest
FLOWISE_USERNAME=admin
FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRET}

# =============================================================================
# n8n
# =============================================================================
N8N_VERSION=latest
N8N_BASIC_AUTH_USER=admin
N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

# =============================================================================
# Ollama
# =============================================================================
OLLAMA_VERSION=latest

# =============================================================================
# Qdrant
# =============================================================================
QDRANT_VERSION=latest
QDRANT_API_KEY=${QDRANT_API_KEY}

# =============================================================================
# Langfuse
# =============================================================================
LANGFUSE_VERSION=2
LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET}
LANGFUSE_NEXT_AUTH_SECRET=${LANGFUSE_AUTH_SECRET}
LANGFUSE_SALT=${LANGFUSE_SALT}
LANGFUSE_DB_PASSWORD=${LANGFUSE_DB_PASS}

# =============================================================================
# Traefik
# =============================================================================
TRAEFIK_VERSION=v3.3

# =============================================================================
# Dify
# =============================================================================
DIFY_VERSION=1.13.3
DIFY_SECRET_KEY=${DIFY_SECRET}
DIFY_DB_PASSWORD=${DIFY_DB_PASS}
DIFY_REDIS_PASSWORD=${DIFY_REDIS_PASS}
DIFY_SANDBOX_KEY=${DIFY_SANDBOX_KEY}
DIFY_SANDBOX_VERSION=0.2.14
DIFY_PLUGIN_VERSION=0.5.3-local
DIFY_PLUGIN_DAEMON_KEY=${DIFY_PLUGIN_DAEMON_KEY}
DIFY_PLUGIN_INNER_API_KEY=${DIFY_PLUGIN_INNER_KEY}
EOF

chmod 600 "${ENV_FILE}"

# --- Write .secrets reference ---
cat > "${SECRETS_FILE}" << EOF
# AI Lab — Generated Secrets Reference
# Created: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Domain:  ${DOMAIN}
#
# Keep this file safe. It is gitignored and will NOT be committed.
# Delete after noting down credentials you need.

=== Access URLs ===
Dify:     https://dify.${DOMAIN}
Flowise:  https://flow.${DOMAIN}
n8n:      https://n8n.${DOMAIN}
Langfuse: https://trace.${DOMAIN}

=== Flowise ===
Username: admin
Password: ${FLOWISE_PASSWORD}

=== n8n ===
Username: admin
Password: ${N8N_PASSWORD}

=== Qdrant ===
API Key:  ${QDRANT_API_KEY}

=== Langfuse ===
(Admin account created on first visit via web UI)
DB Password: ${LANGFUSE_DB_PASS}

=== Dify ===
(Admin account created on first visit via setup wizard)
DB Password: ${DIFY_DB_PASS}
EOF

chmod 600 "${SECRETS_FILE}"

echo ""
echo "============================================="
echo "  .env generated successfully"
echo "============================================="
echo "  Domain:  ${DOMAIN}"
echo "  Email:   ${ACME_EMAIL}"
echo "  Secrets: ${SECRETS_FILE}"
echo ""
echo "  Next steps:"
echo "    docker compose up -d"
echo "    cat .secrets    # view credentials"
echo "============================================="
